### ISSUE TITLE
Is it intentional that the password must *not* contain any primary Griffin family character?

### ISSUE THREAD

**Issue by jmorahan** [troyhunt/password-purgatory-api#15]
The logic (apart from the regex issue addressed in #14) is implemented correctly for what the badPasswordMessage says, but ... that particular rule seems unlikely to cause pain to the spammer in the vast majority of cases. Should it be inverted?

**Comment by Greenlio** [comment]
Why? There's no purpose to be inverted. There's no world where someone 'accidentally' puts a Family Guy family character.

**Comment by jmorahan** [comment]
That's the point. Currently the rule checks that the password doesn't contain a character name, and only complains if it does.

Peter and Stewie don't work because of the other bug, but try this:

https://api.passwordpurgatory.com/make-hell?password=Marge1!%C3%A4%CE%B1Lois

I think it should complain when there is *not* a Family Guy character, rather than when there *is*.

**Comment by Greenlio** [comment]
Oh.. I see. I didn't see that. Yeah, that should be done.
