### ISSUE TITLE
No copy / paste

### ISSUE THREAD

**Issue by MichaelNMaggs** [troyhunt/password-purgatory-api#50]
A message that Troy might be happy to see :)

"For security reasons you cannot use copy/paste in this field"

I'm putting this up as a tentative suggestion, as it might possibily result in people bailing out sooner than they would otherwise do

**Comment by ubalklen** [comment]
This is the API repo. I don't think this cab be implemented at this level (but it can definitely be applied to an app that consumes the API).

**Comment by troyhunt** [comment]
Just so this isn't left hanging open for ages, I've added some objectives to the readme file outlining how we really need to keep the API focused on criteria that can be assessed at the other end of an HTTP request whilst this idea is effectively a client-side control.
