### ISSUE TITLE
Add a captcha

### ISSUE THREAD

**Issue by ubalklen** [troyhunt/password-purgatory-api#63]
Demand captcha solving after some attempts. This can be a new purgatory on its own. Some suggestions:

- make them difficult to read
- include lots of ambiguities (is that a B or 13?)
- make them randomly fail, even if properly answered
- ask for a solution of a hard math problem

**Comment by troyhunt** [comment]
Just so this isn't left hanging open for ages, I've added some objectives to the readme file outlining how we really need to keep the API focused on criteria that can be assessed at the other end of an HTTP request whilst this idea is effectively a client-side control.
