### ISSUE TITLE
CloudFlare gives an error with code 1101

### ISSUE THREAD

**Issue by oittaa** [troyhunt/password-purgatory-api#9]
This works and outputs `"message": "Password must contain at least 1 Greek character"`
https://api.passwordpurgatory.com/make-hell?password=Marge1!%C3%A4

This gives `Error 1101`
https://api.passwordpurgatory.com/make-hell?password=Marge1!%C3%A4%CE%B1

I'm not familiar with CloudFlare workers, but the error probably happens around line 37. There's also a typo on line 34, where the condition is `!== null` when it probably should be `=== null` and that condition is just basically skipped in these examples.

https://github.com/troyhunt/password-purgatory-api/blob/b0967e40d57b4c9d5c02f83b338d9d30cd3369e8/index.js#L34-L39

**Comment by olikami** [comment]
It's a syntax error in the emoticon regex.

```
SyntaxError: Invalid regular expression: //:‑)|:)|:-]|:]|:>|:-}|:}|:o))|:^)|=]|=)|:]|:->|:>|8-)|:-}|:}|:o)|:^)|=]|=)|:‑D|:D|B^D|:‑(|:(|:‑<|:<|:‑[|:[|:-|||>:[|:{|:(|;(|:'‑(|:'(|:=(|:'‑)|:')|:"D|:‑O|:O|:‑o|:o|:-0|>:O|>:3|;‑)|;)|;‑]|;^)|:‑P|:-/|:/|:‑.|>:|>:/|:|:‑||:||>:‑)|>:)|}:‑)|>;‑)|>;)|>:3||;‑)|:‑J|<:‑||~:>/g/: Unmatched ')' at line 0, col -2
```

**Comment by LucaBlackDragon** [comment]
I'm getting a 1101 error too.
Password: `hunTerBart2456456æα`
Ray ID: `6e9c2f5e7a8b5a43`
The error triggered when I added the final alpha
